---
- hosts: webservers
  become: yes
  roles:
    - baseline
  tasks:
    - name: install apache
      apt: name=apache2 state=latest
    - name: start and enable apache
      service: name=apache2 state=started enabled=yes