---
- hosts: webservers
  become: yes
  vars_files:
    - /home/ansible/adv-ansible/labs/ansible-vault/conf/confidential
  tasks:
    - name: install httpd
      apt:
        name: apache2
        state: latest
      notify: httpd service
      tags:
        - base-install
    - name: create apache config directory
      file:
         path: "/etc/httpd/conf.d"
         state: directory
         mode: '0755'
    - name: create another directory
      file:
         path: "/etc/httpd/conf"
         state: directory
         mode: '0755'
    - name: configure virtual host
      template:
        src: /home/ansible/adv-ansible/labs/ansible-vault/conf/vhost.conf.j2
        dest: /etc/httpd/conf.d/vhost.conf
      notify: httpd service
      tags:
        - vhost
    - name: configure site auth
      template:
        src: /home/ansible/adv-ansible/labs/ansible-vault/conf/htpasswd.j2
        dest: /etc/httpd/conf/htpasswd
      notify: httpd service
      tags:
        - vhost        
  handlers:
    - name: Restart and enable httpd
      service:
        name: apache2
        state: restarted
        enabled: yes
      listen: httpd service